name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build Extension
        run: |
          chmod +x gradlew
          ./gradlew make

      - name: Deploy to Builds Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: builds
          folder: builds
          clean: true
